# Generated by Django 4.2.8 on 2023-12-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
