# Generated by Django 4.2.8 on 2023-12-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_manager',
        ),
    ]
